version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando Angular CLI y dependencias..."
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo "Compilando el proyecto Angular..."
      - ng build --configuration production
  post_build:
    commands:
      - echo "Compilación completada correctamente."

artifacts:
  files:
    - '**/*'
  base-directory: dist/frontend-trinoflow
  discard-paths: no
