version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando Angular CLI y dependencias..."
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo "Compilando proyecto Angular en producción..."
      - ng build --configuration production
artifacts:
  files:
    - '**/*'
  base-directory: dist/frontend-trinoflow
